export default syntax => ({
  name: "Noctis Bordo",
  type: "dark",
  colors: {
    // ---------------------------
    // Editor Base Colors
    // ---------------------------
    "selection.background": "#88445cbb",
    descriptionForeground: "#bb778f",
    errorForeground: "#e34e1c",
    "widget.shadow": "#00000044",
    "editor.background": "#322a2d",
    "editor.foreground": "#cbbec2",
    "editorLineNumber.foreground": "#715b63",
    "editorLineNumber.activeForeground": "#bb778f",
    "editorCursor.foreground": "#ffb3cd",
    // ---------------------------
    // Badge
    // ---------------------------
    "badge.background": "#f18eb0",
    "badge.foreground": "#1f191b",
    // ---------------------------
    // Activity Bar
    // ---------------------------
    "activityBar.background": "#322a2d",
    "activityBar.dropBackground": "#bb778f65",
    "activityBar.border": "#1f191b",
    "activityBar.foreground": "#997582",
    "activityBar.inactiveForeground": "#99758277",
    "activityBarBadge.background": "#f18eb0",
    "activityBarBadge.foreground": "#1f191b",
    "activityBar.activeBackground": "#f18eb033",
    "activityBar.activeBorder": "#f18eb0",
    // ---------------------------
    // Sidebar
    // ---------------------------
    "sideBar.background": "#2c2528",
    "sideBar.dropBackground": "#2c2528",
    "sideBar.border": "#1f191b",
    "sideBar.foreground": "#bbaab0",
    "sideBarSectionHeader.background": "#413036",
    "sideBarSectionHeader.foreground": "#bbaab0",
    "sideBarTitle.foreground": "#bbaab0",
    "sideBarSectionHeader.border": "#1f191b",
    // ---------------------------
    // Status Bar
    // ---------------------------
    "statusBar.foreground": "#997582",
    "statusBar.background": "#322a2d",
    "statusBar.border": "#1f191b",
    "statusBar.debuggingBackground": "#322a2d",
    "statusBar.debuggingForeground": "#ff80ac50",
    "statusBar.debuggingBorder": "#ff80acaf",
    "statusBar.noFolderForeground": "#a48e96",
    "statusBar.noFolderBackground": "#322a2d",
    "statusBar.noFolderBorder": "#322a2d",
    "statusBarItem.activeBackground": "#8f566a77",
    "statusBarItem.hoverBackground": "#8f566a33",
    "statusBarItem.prominentBackground": "#272022",
    "statusBarItem.prominentHoverBackground": "#43142488",
    // ---------------------------
    // Button
    // ---------------------------
    "button.background": "#007f99",
    "button.foreground": "#edebff",
    "button.hoverBackground": "#0ac",
    // ---------------------------
    // Dropdown
    // ---------------------------
    "dropdown.background": "#413036",
    "dropdown.border": "#413036",
    "dropdown.foreground": "#bb778f",
    // ---------------------------
    // Editor Marker Navigation
    // ---------------------------
    "editorMarkerNavigation.background": "#5f3a4729",
    "editorMarkerNavigationError.background": "#e34e1c",
    "editorMarkerNavigationWarning.background": "#e69533",
    // ---------------------------
    // Errors and warnings
    // ---------------------------
    "editorError.border": "#322a2d",
    "editorError.foreground": "#e34e1c",
    "editorWarning.border": "#322a2d",
    "editorWarning.foreground": "#e69533",
    "editorInfo.border": "#322a2d",
    "editorInfo.foreground": "#40d4e7",
    "editorHint.border": "#49e9a600",
    "editorHint.foreground": "#49e9a6",
    // ---------------------------
    // Editor Groups and Tabs
    // ---------------------------
    "editorGroup.emptyBackground": "#715b6333",
    "editorGroup.border": "#1f191b",
    "editorGroup.dropBackground": "#715b6333",
    // ---------------------------
    // Editor Group Header
    // ---------------------------
    "editorGroupHeader.noTabsBackground": "#413036",
    "editorGroupHeader.tabsBackground": "#413036",
    "editorGroupHeader.tabsBorder": "#413036",
    // ---------------------------
    // Editor Tabs
    // ---------------------------
    "tab.activeBackground": "#322a2d",
    "tab.unfocusedActiveBackground": "#38232b",
    "tab.activeForeground": "#f18eb0",
    "tab.border": "#1f191b",
    "tab.inactiveBackground": "#413036",
    "tab.inactiveForeground": "#bbaab0",
    "tab.unfocusedActiveForeground": "#bbaab0",
    "tab.unfocusedInactiveForeground": "#bbaab0",
    "tab.activeBorderTop": "#f18eb0",
    "tab.activeModifiedBorder": "#49e9a6",
    "tab.activeBorder": "#322a2d",
    "tab.unfocusedActiveBorder": "#322a2d",
    "tab.unfocusedHoverBackground": "#f18eb021",
    // ---------------------------
    // Text Colors
    // ---------------------------
    "textBlockQuote.background": "#322a2d",
    "textBlockQuote.border": "#997582",
    "textCodeBlock.background": "#322a2d",
    "textLink.activeForeground": "#f18eb0",
    "textLink.foreground": "#f18eb0",
    "textPreformat.foreground": "#ffc180",
    "textSeparator.foreground": "#322a2d",
    // ---------------------------
    // Welcome Page
    // ---------------------------
    "walkThrough.embeddedEditorBackground": "#322a2d",
    "welcomePage.buttonBackground": "#272022",
    "welcomePage.buttonHoverBackground": "#413036",
    // ---------------------------
    // Input Control
    // ---------------------------
    "input.background": "#272022",
    "input.border": "#412a32",
    "input.foreground": "#ddd5d7",
    "input.placeholderForeground": "#a48e96",
    "inputOption.activeBorder": "#997582",
    "inputValidation.errorForeground": "#ff4000",
    "inputValidation.errorBackground": "#501502ee",
    "inputValidation.errorBorder": "#691c02",
    "inputValidation.infoForeground": "#40d4e7",
    "inputValidation.infoBackground": "#0f6e7bee",
    "inputValidation.infoBorder": "#148f9f",
    "inputValidation.warningForeground": "#e69533",
    "inputValidation.warningBackground": "#82694acc",
    "inputValidation.warningBorder": "#a88457",
    // ---------------------------
    // Editor Widgets
    // ---------------------------
    "editorWidget.background": "#413036",
    "editorWidget.border": "#1f191b",
    "editorHoverWidget.background": "#3e2e33",
    "editorHoverWidget.border": "#1f191b",
    "editorSuggestWidget.background": "#3e2e33",
    "editorSuggestWidget.border": "#1f191b",
    "editorSuggestWidget.foreground": "#bbaab0",
    "editorSuggestWidget.highlightForeground": "#f18eb0",
    "editorSuggestWidget.selectedBackground": "#563440",
    // ---------------------------
    // Gutter
    // ---------------------------
    "editorGutter.background": "#322a2d",
    "editorGutter.addedBackground": "#8ce99a",
    "editorGutter.deletedBackground": "#e34e1c",
    "editorGutter.modifiedBackground": "#ffc180",
    // ---------------------------
    // Selection Colors
    // ---------------------------
    "editor.selectionBackground": "#99758255",
    "editor.selectionHighlightBackground": "#7f536299",
    "editor.inactiveSelectionBackground": "#99758233",
    "editor.wordHighlightStrongBackground": "#cc990033",
    "editor.wordHighlightBackground": "#e4b78133",
    "editor.findMatchBackground": "#40bf6a11",
    "editor.findMatchHighlightBackground": "#0e667179",
    "editor.findRangeHighlightBackground": "#49e9a622",
    "editor.hoverHighlightBackground": "#9975823f",
    "editor.lineHighlightBackground": "#453138aa",
    "editor.lineHighlightBorder": "#45313899",
    "editor.rangeHighlightBackground": "#49d6e922",
    "editorLink.activeForeground": "#14a5ff",
    "editorWhitespace.foreground": "#ffccde21",
    "editorIndentGuide.background": "#48373d",
    "editorIndentGuide.activeBackground": "#7f5362",
    "editorBracketMatch.background": "#99758222",
    "editorBracketMatch.border": "#997582",
    "editorRuler.foreground": "#593a46",
    // ---------------------------
    // Code Lens
    // ---------------------------
    "editorCodeLens.foreground": "#776284",
    // ---------------------------
    // Integrated Terminal Colors
    // ---------------------------
    "terminal.ansiBlack": "#47393e",
    "terminal.ansiRed": "#e66533",
    "terminal.ansiGreen": "#49e9a6",
    "terminal.ansiYellow": "#e4b781",
    "terminal.ansiBlue": "#49ace9",
    "terminal.ansiMagenta": "#df769b",
    "terminal.ansiCyan": "#49d6e9",
    "terminal.ansiWhite": "#b9acb0",
    "terminal.ansiBrightBlack": "#69545b",
    "terminal.ansiBrightRed": "#e97749",
    "terminal.ansiBrightGreen": "#60ebb1",
    "terminal.ansiBrightYellow": "#e69533",
    "terminal.ansiBrightBlue": "#60b6eb",
    "terminal.ansiBrightMagenta": "#e798b3",
    "terminal.ansiBrightCyan": "#60dbeb",
    "terminal.ansiBrightWhite": "#cbbec2",
    "terminal.background": "#272022",
    "terminal.foreground": "#cbbec2",
    "terminalCursor.background": "#272022",
    "terminalCursor.foreground": "#cbbec2",
    // ---------------------------
    // Merge Conflicts
    // ---------------------------
    "merge.border": "#322a2d00",
    "merge.currentContentBackground": "#85f1ff22",
    "merge.currentHeaderBackground": "#85f1ff44",
    "merge.incomingContentBackground": "#9d92f222",
    "merge.incomingHeaderBackground": "#9d92f244",
    "merge.commonContentBackground": "#ffc18022",
    "merge.commonHeaderBackground": "#ffc18044",
    "editorOverviewRuler.currentContentForeground": "#85f1ff44",
    "editorOverviewRuler.incomingContentForeground": "#9d92f244",
    "editorOverviewRuler.commonContentForeground": "#ffc18044",
    "editorOverviewRuler.border": "#322a2d",
    // ---------------------------
    // Notification Colors
    // ---------------------------
    "notificationCenter.border": "#413036",
    "notificationCenterHeader.foreground": "#a48e96",
    "notificationCenterHeader.background": "#413036",
    "notificationToast.border": "#413036",
    "notifications.foreground": "#ddd5d7",
    "notifications.background": "#413036",
    "notifications.border": "#413036",
    "notificationLink.foreground": "#a48e96",
    // ---------------------------
    // Diff
    // ---------------------------
    "diffEditor.insertedTextBackground": "#16b67327",
    "diffEditor.removedTextBackground": "#e6653341",
    // ---------------------------
    // Debug
    // ---------------------------
    "debugToolBar.background": "#322a2d",
    "debugExceptionWidget.background": "#322a2d",
    "debugExceptionWidget.border": "#997582",
    // ---------------------------
    // Extensions
    // ---------------------------
    "extensionButton.prominentBackground": "#008c99",
    "extensionButton.prominentForeground": "#e4e2f9",
    "extensionButton.prominentHoverBackground": "#00bbcc",
    focusBorder: "#413036",
    foreground: "#cbbec2",
    // ---------------------------
    // Panel
    // ---------------------------
    "panel.background": "#272022",
    "panel.border": "#997582",
    "panelTitle.activeBorder": "#997582",
    "panelTitle.activeForeground": "#f18eb0",
    "panelTitle.inactiveForeground": "#936c7a",
    // ---------------------------
    // Peek View Colors
    // ---------------------------
    "peekView.border": "#997582",
    "peekViewEditor.background": "#2c2125",
    "peekViewEditor.matchHighlightBackground": "#88445c55",
    "peekViewEditorGutter.background": "#2c2125",
    "peekViewResult.background": "#322529",
    "peekViewResult.fileForeground": "#ffc180",
    "peekViewResult.lineForeground": "#a48e96",
    "peekViewResult.matchHighlightBackground": "#47393e",
    "peekViewResult.selectionBackground": "#47393e",
    "peekViewResult.selectionForeground": "#a48e96",
    "peekViewTitle.background": "#322529",
    "peekViewTitleDescription.foreground": "#a48e96",
    "peekViewTitleLabel.foreground": "#ffc180",
    // ---------------------------
    // Progress Bar
    // ---------------------------
    "progressBar.background": "#f18eb0",
    // ---------------------------
    // Scrollbar
    // ---------------------------
    "scrollbar.shadow": "#00000044",
    "scrollbarSlider.activeBackground": "#eb609155",
    "scrollbarSlider.background": "#eb609133",
    "scrollbarSlider.hoverBackground": "#eb609144",
    // ---------------------------
    // Git status colors in File Explorer
    // ---------------------------
    "gitDecoration.addedResourceForeground": "#16b673",
    "gitDecoration.modifiedResourceForeground": "#49e9a6",
    "gitDecoration.deletedResourceForeground": "#e34e1c",
    "gitDecoration.untrackedResourceForeground": "#40d4e7",
    "gitDecoration.ignoredResourceForeground": "#5b788b",
    "gitDecoration.conflictingResourceForeground": "#ffc180",
    // ---------------------------
    // Quick Picker
    // ---------------------------
    "pickerGroup.border": "#997582",
    "pickerGroup.foreground": "#f18eb0",
    // ---------------------------
    // Lists and Trees
    // ---------------------------
    "list.activeSelectionBackground": "#5c2e3e99",
    "list.activeSelectionForeground": "#edebff",
    "list.dropBackground": "#38292e",
    "list.focusBackground": "#824a5e66",
    "list.focusForeground": "#edebff",
    "list.highlightForeground": "#f18eb0",
    "list.hoverBackground": "#533641",
    "list.hoverForeground": "#edebff",
    "list.inactiveFocusBackground": "#2c2528",
    "list.inactiveSelectionBackground": "#3b2b31",
    "list.inactiveSelectionForeground": "#cbbec2",
    "list.errorForeground": "#e34e1c",
    "list.warningForeground": "#ffa857",
    "listFilterWidget.background": "#202040",
    "listFilterWidget.outline": "#49e9a6",
    "listFilterWidget.noMatchesOutline": "#e34e1c",
    "tree.indentGuidesStroke": "#715b63",
    // ---------------------------
    // Settings Editor Colors
    // ---------------------------
    "settings.headerForeground": "#cbbec2",
    "settings.modifiedItemIndicator": "#15ac31",
    "settings.dropdownListBorder": "#824a5e77",
    "settings.dropdownBackground": "#413036",
    "settings.dropdownForeground": "#0ac",
    "settings.dropdownBorder": "#413036",
    "settings.checkboxBackground": "#413036",
    "settings.checkboxForeground": "#0ac",
    "settings.checkboxBorder": "#413036",
    "settings.textInputBackground": "#413036",
    "settings.textInputForeground": "#0ac",
    "settings.textInputBorder": "#413036",
    "settings.numberInputBackground": "#272022",
    "settings.numberInputForeground": "#7060eb",
    "settings.numberInputBorder": "#272022",
    // ---------------------------
    // Breadcrumbs
    // ---------------------------
    "breadcrumb.foreground": "#bbaab0",
    "breadcrumb.background": "#322a2d",
    "breadcrumb.focusForeground": "#f18eb0",
    "breadcrumb.activeSelectionForeground": "#edebff",
    "breadcrumbPicker.background": "#413036",
    // ---------------------------
    // Title bar
    // Note: These colors are currently only supported on macOS.
    // ---------------------------
    "titleBar.activeBackground": "#322a2d",
    "titleBar.activeForeground": "#cbbec2",
    "titleBar.inactiveBackground": "#322a2d",
    "titleBar.inactiveForeground": "#bbaab0",
    // ---------------------------
    // Custom title bar and menus
    // Note: These colors are currently only supported on Windows and Linux.
    // ---------------------------
    "menu.background": "#413036",
    "menu.foreground": "#bbaab0",
    "menu.selectionBackground": "#824a5e66",
    "menu.selectionForeground": "#f18eb0",
    "menu.selectionBorder": "#824a5e66",
    "menu.separatorBackground": "#f18eb0",
    "menubar.selectionBackground": "#824a5e66",
    "menubar.selectionForeground": "#f18eb0",
    "menubar.selectionBorder": "#824a5e66",
    // ---------------------------
    // Snippets
    // ---------------------------
    "editor.snippetTabstopHighlightBackground": "#272022",
    "editor.snippetTabstopHighlightBorder": "#2c2528",
    "editor.snippetFinalTabstopHighlightBackground": "#272022",
    "editor.snippetFinalTabstopHighlightBorder": "#2c2528",
    // ---------------------------
    // Minimap
    // ---------------------------
    "minimap.findMatchHighlight": "#f18eb0ee",
    "minimap.errorHighlight": "#e34e1cee",
    "minimap.warningHighlight": "#e69533ee",
    "minimapGutter.addedBackground": "#16b673",
    "minimapGutter.modifiedBackground": "#49e9a6",
    "minimapGutter.deletedBackground": "#e34e1c",
    "minimap.background": "#322a2d99"
  },
  tokenColors: syntax
});
