export default syntax => ({
   name: "Noctis Obscuro",
   type: "dark",
   colors: {
      // ---------------------------
      // Editor Base Colors
      // ---------------------------
      "selection.background": "#0e657177",
      descriptionForeground: "#929ea0",
      errorForeground: "#e34e1c",
      "widget.shadow": "#00000044",
      "editor.background": "#041d20",
      "editor.foreground": "#b2cacd",
      "editorLineNumber.foreground": "#4e6b6e",
      "editorLineNumber.activeForeground": "#169fb1",
      "editorCursor.foreground": "#85efff",
      // ---------------------------
      // Badge
      // ---------------------------
      "badge.background": "#169fb1",
      "badge.foreground": "#0f1415",
      // ---------------------------
      // Activity Bar
      // ---------------------------
      "activityBar.background": "#041d20",
      "activityBar.dropBackground": "#929ea065",
      "activityBar.border": "#0f1415",
      "activityBar.foreground": "#169fb1",
      "activityBar.inactiveForeground": "#169fb177",
      "activityBarBadge.background": "#169fb1",
      "activityBarBadge.foreground": "#0f1415",
      // ---------------------------
      // Sidebar
      // ---------------------------
      "sideBar.background": "#052629",
      "sideBar.dropBackground": "#042124",
      "sideBar.border": "#0f1415",
      "sideBar.foreground": "#a5b5b5",
      "sideBarSectionHeader.background": "#083d44",
      "sideBarSectionHeader.foreground": "#a5b5b5",
      "sideBarTitle.foreground": "#a5b5b5",
      "sideBarSectionHeader.border": "#0f1415",
      // ---------------------------
      // Status Bar
      // ---------------------------
      "statusBar.foreground": "#169fb1",
      "statusBar.background": "#041d20",
      "statusBar.border": "#0f1415",
      "statusBar.debuggingBackground": "#041d20",
      "statusBar.debuggingForeground": "#df769b50",
      "statusBar.debuggingBorder": "#df769baf",
      "statusBar.noFolderForeground": "#87a7ab",
      "statusBar.noFolderBackground": "#041d20",
      "statusBar.noFolderBorder": "#041d20",
      "statusBarItem.activeBackground": "#19bacc45",
      "statusBarItem.hoverBackground": "#062e32",
      "statusBarItem.prominentBackground": "#020c0e",
      "statusBarItem.prominentHoverBackground": "#00292e",
      // ---------------------------
      // Button
      // ---------------------------
      "button.background": "#099",
      "button.foreground": "#ebfdff",
      "button.hoverBackground": "#0cc",
      // ---------------------------
      // Dropdown
      // ---------------------------
      "dropdown.background": "#041d20",
      "dropdown.border": "#041d20",
      "dropdown.foreground": "#87a7ab",
      // ---------------------------
      // Editor Marker Navigation
      // ---------------------------
      "editorMarkerNavigation.background": "#3a3a5e29",
      "editorMarkerNavigationError.background": "#e34e1c",
      "editorMarkerNavigationWarning.background": "#e69533",
      // ---------------------------
      // Errors and warnings
      // ---------------------------
      "editorError.border": "#041d20",
      "editorError.foreground": "#e34e1c",
      "editorWarning.border": "#041d20",
      "editorWarning.foreground": "#e69533",
      "editorInfo.border": "#041d20",
      "editorInfo.foreground": "#40d4e7",
      "editorHint.border": "#49e9a680",
      "editorHint.foreground": "#49e9a6",
      // ---------------------------
      // Editor Groups and Tabs
      // ---------------------------
      "editorGroup.emptyBackground": "#5f6b6d33",
      "editorGroup.border": "#0f1415",
      "editorGroup.dropBackground": "#5f6b6d33",
      // ---------------------------
      // Editor Group Header
      // ---------------------------
      "editorGroupHeader.noTabsBackground": "#062e32",
      "editorGroupHeader.tabsBackground": "#062e32",
      "editorGroupHeader.tabsBorder": "#062e32",
      // ---------------------------
      // Editor Tabs
      // ---------------------------
      "tab.activeBackground": "#041d20",
      "tab.activeForeground": "#ebfdff",
      "tab.border": "#0f1415",
      "tab.inactiveBackground": "#062e32",
      "tab.inactiveForeground": "#87a7ab",
      "tab.unfocusedActiveForeground": "#87a7ab",
      "tab.unfocusedInactiveForeground": "#87a7ab",
      "tab.activeBorderTop": "#40d4e7",
      "tab.activeModifiedBorder": "#49e9a6",
      "tab.activeBorder": "#041d20",
      "tab.unfocusedActiveBorder": "#041d20",
      "tab.unfocusedHoverBackground": "#169fb121",
      // ---------------------------
      // Text Colors
      // ---------------------------
      "textBlockQuote.background": "#041d20",
      "textBlockQuote.border": "#16a3b6",
      "textCodeBlock.background": "#041d20",
      "textLink.activeForeground": "#40d4e7",
      "textLink.foreground": "#40d4e7",
      "textPreformat.foreground": "#e4b781",
      "textSeparator.foreground": "#041d20",

      // ---------------------------
      // Welcome Page
      // ---------------------------
      "walkThrough.embeddedEditorBackground": "#041d20",
      "welcomePage.buttonBackground": "#052529",
      "welcomePage.buttonHoverBackground": "#062e32",
      // ---------------------------
      // Input Control
      // ---------------------------
      "input.background": "#052529",
      "input.border": "#083f44",
      "input.foreground": "#CDD3DE",
      "input.placeholderForeground": "#87a7ab",
      "inputOption.activeBorder": "#169fb1",
      "inputValidation.errorForeground": "#ff4000",
      "inputValidation.errorBackground": "#501502ee",
      "inputValidation.errorBorder": "#691c02",
      "inputValidation.infoForeground": "#40d4e7",
      "inputValidation.infoBackground": "#0f6e7bee",
      "inputValidation.infoBorder": "#148f9f",
      "inputValidation.warningForeground": "#e69533",
      "inputValidation.warningBackground": "#82694acc",
      "inputValidation.warningBorder": "#a88457",
      // ---------------------------
      // Editor Widgets
      // ---------------------------
      "editorWidget.background": "#062e32",
      "editorWidget.border": "#0f1415",
      "editorHoverWidget.background": "#062e32",
      "editorHoverWidget.border": "#0f1415",
      "editorSuggestWidget.background": "#062e32",
      "editorSuggestWidget.border": "#0f1415",
      "editorSuggestWidget.foreground": "#87a7ab",
      "editorSuggestWidget.highlightForeground": "#40d4e7",
      "editorSuggestWidget.selectedBackground": "#0e6671",
      // ---------------------------
      // Gutter
      // ---------------------------
      "editorGutter.background": "#041d20",
      "editorGutter.addedBackground": "#8ce99a",
      "editorGutter.deletedBackground": "#e34e1c",
      "editorGutter.modifiedBackground": "#e4b781",
      // ---------------------------
      // Selection Colors
      // ---------------------------
      "editor.selectionBackground": "#169fb144",
      "editor.selectionHighlightBackground": "#49ace944",
      "editor.inactiveSelectionBackground": "#0e657155",
      "editor.wordHighlightStrongBackground": "#cc990033",
      "editor.wordHighlightBackground": "#e4b78133",
      "editor.findMatchBackground": "#49e9a644",
      "editor.findMatchHighlightBackground": "#0e667179",
      "editor.findRangeHighlightBackground": "#49e9a633",
      "editor.hoverHighlightBackground": "#169fb13f",
      "editor.lineHighlightBackground": "#083d44ee",
      "editor.lineHighlightBorder": "#083d44",
      "editor.rangeHighlightBackground": "#083d44a1",
      "editorLink.activeForeground": "#14a5ff",
      "editorWhitespace.foreground": "#ffffff21",
      "editorIndentGuide.background": "#223b3f",
      "editorIndentGuide.activeBackground": "#3e6f74",
      "editorBracketMatch.background": "#169fb122",
      "editorBracketMatch.border": "#169fb1",
      "editorRuler.foreground": "#243f42",
      // ---------------------------
      // Code Lens
      // ---------------------------
      "editorCodeLens.foreground": "#507b95",
      // ---------------------------
      // Integrated Terminal Colors
      // ---------------------------
      "terminal.ansiBlack": "#6b797b",
      "terminal.ansiRed": "#e66533",
      "terminal.ansiGreen": "#49e9a6",
      "terminal.ansiYellow": "#e4b781",
      "terminal.ansiBlue": "#49ace9",
      "terminal.ansiMagenta": "#df769b",
      "terminal.ansiCyan": "#49d6e9",
      "terminal.ansiWhite": "#c5dee2",
      "terminal.ansiBrightBlack": "#5b858b",
      "terminal.ansiBrightRed": "#e34e1c",
      "terminal.ansiBrightGreen": "#00ff95",
      "terminal.ansiBrightYellow": "#e69533",
      "terminal.ansiBrightBlue": "#009dff",
      "terminal.ansiBrightMagenta": "#ff5792",
      "terminal.ansiBrightCyan": "#6bffff",
      "terminal.ansiBrightWhite": "#dbfbff",
      "terminal.background": "#052a2e",
      "terminal.foreground": "#b2cacd",
      "terminalCursor.background": "#052a2e",
      "terminalCursor.foreground": "#b2cacd",
      // ---------------------------
      // Merge Conflicts
      // ---------------------------
      "merge.border": "#041d20",
      "merge.currentContentBackground": "#85f1ff22",
      "merge.currentHeaderBackground": "#85f1ff44",
      "merge.incomingContentBackground": "#9d92f222",
      "merge.incomingHeaderBackground": "#9d92f244",
      "merge.commonContentBackground": "#ffc18022",
      "merge.commonHeaderBackground": "#ffc18044",
      "editorOverviewRuler.currentContentForeground": "#85f1ff44",
      "editorOverviewRuler.incomingContentForeground": "#9d92f244",
      "editorOverviewRuler.commonContentForeground": "#ffc18044",
      "editorOverviewRuler.border": "#041d20",
      // ---------------------------
      // Notification Colors
      // ---------------------------
      "notificationCenter.border": "#062e32",
      "notificationCenterHeader.foreground": "#87a7ab",
      "notificationCenterHeader.background": "#062e32",
      "notificationToast.border": "#062e32",
      "notifications.foreground": "#CDD3DE",
      "notifications.background": "#062e32",
      "notifications.border": "#062e32",
      "notificationLink.foreground": "#87a7ab",
      // ---------------------------
      // Diff
      // ---------------------------
      "diffEditor.insertedTextBackground": "#b2f2bb17",
      "diffEditor.insertedTextBorder": "#b2f2bb17",
      "diffEditor.removedTextBackground": "#bb200533",
      "diffEditor.removedTextBorder": "#bb200533",
      // ---------------------------
      // Debug
      // ---------------------------
      "debugToolBar.background": "#041d20",
      "debugExceptionWidget.background": "#041d20",
      "debugExceptionWidget.border": "#16a3b6",
      // ---------------------------
      // Extensions
      // ---------------------------
      "extensionButton.prominentBackground": "#099",
      "extensionButton.prominentForeground": "#e5f5f5",
      "extensionButton.prominentHoverBackground": "#0cc",
      focusBorder: "#062e32",
      foreground: "#b2cacd",
      // ---------------------------
      // Panel
      // ---------------------------
      "panel.background": "#052a2e",
      "panel.border": "#0e6671",
      "panelTitle.activeBorder": "#0e6671",
      "panelTitle.activeForeground": "#40d4e7",
      "panelTitle.inactiveForeground": "#87a7ab",
      // ---------------------------
      // Peek View Colors
      // ---------------------------
      "peekView.border": "#169fb1",
      "peekViewEditor.background": "#002124",
      "peekViewEditor.matchHighlightBackground": "#00718079",
      "peekViewEditor.matchHighlightBorder": "#007180cc",
      "peekViewEditorGutter.background": "#002124",
      "peekViewResult.background": "#041d20",
      "peekViewResult.fileForeground": "#e4b781",
      "peekViewResult.lineForeground": "#87a7ab",
      "peekViewResult.matchHighlightBackground": "#062e32",
      "peekViewResult.selectionBackground": "#062e32",
      "peekViewResult.selectionForeground": "#87a7ab",
      "peekViewTitle.background": "#041d20",
      "peekViewTitleDescription.foreground": "#87a7ab",
      "peekViewTitleLabel.foreground": "#e4b781",
      // ---------------------------
      // Progress Bar
      // ---------------------------
      "progressBar.background": "#40d4e7",
      // ---------------------------
      // Scrollbar
      // ---------------------------
      "scrollbar.shadow": "#00000044",
      "scrollbarSlider.activeBackground": "#169fb1ad",
      "scrollbarSlider.background": "#6a90955b",
      "scrollbarSlider.hoverBackground": "#169fb162",
      // ---------------------------
      // Git status colors in File Explorer
      // ---------------------------
      "gitDecoration.addedResourceForeground": "#16b673",
      "gitDecoration.modifiedResourceForeground": "#49e9a6",
      "gitDecoration.deletedResourceForeground": "#e34e1c",
      "gitDecoration.untrackedResourceForeground": "#40d4e7",
      "gitDecoration.ignoredResourceForeground": "#647e82",
      "gitDecoration.conflictingResourceForeground": "#e4b781",
      // ---------------------------
      // Quick Picker
      // ---------------------------
      "pickerGroup.border": "#0e6671",
      "pickerGroup.foreground": "#169fb1",
      // ---------------------------
      // Lists and Trees
      // ---------------------------
      "list.activeSelectionBackground": "#0e6671",
      "list.activeSelectionForeground": "#ebfdff",
      "list.dropBackground": "#00404d",
      "list.focusBackground": "#00404d",
      "list.focusForeground": "#ebfdff",
      "list.highlightForeground": "#40d4e7",
      "list.hoverBackground": "#0b515b",
      "list.hoverForeground": "#ebfdff",
      "list.inactiveFocusBackground": "#062d32",
      "list.inactiveSelectionBackground": "#07353b",
      "list.inactiveSelectionForeground": "#b2cacd",
      "list.errorForeground": "#e34e1c",
      "list.warningForeground": "#ffa487",
      "listFilterWidget.background": "#00404d",
      "listFilterWidget.outline": "#49e9a6",
      "listFilterWidget.noMatchesOutline": "#e34e1c",
      // ---------------------------
      // Settings Editor Colors
      // ---------------------------
      "settings.headerForeground": "#b2cacd",
      "settings.modifiedItemIndicator": "#15ac31",
      "settings.dropdownListBorder": "#0e657188",
      "settings.dropdownBackground": "#073940",
      "settings.dropdownForeground": "#0cc",
      "settings.dropdownBorder": "#073940",
      "settings.checkboxBackground": "#073940",
      "settings.checkboxForeground": "#0cc",
      "settings.checkboxBorder": "#073940",
      "settings.textInputBackground": "#073940",
      "settings.textInputForeground": "#0cc",
      "settings.textInputBorder": "#073940",
      "settings.numberInputBackground": "#062e32",
      "settings.numberInputForeground": "#7060eb",
      "settings.numberInputBorder": "#062e32",
      // ---------------------------
      // Breadcrumbs
      // ---------------------------
      "breadcrumb.foreground": "#87a7ab",
      "breadcrumb.background": "#041d20",
      "breadcrumb.focusForeground": "#40d4e7",
      "breadcrumb.activeSelectionForeground": "#ebfdff",
      "breadcrumbPicker.background": "#062e32",
      // ---------------------------
      // Title bar
      // Note: These colors are currently only supported on macOS.
      // ---------------------------
      "titleBar.activeBackground": "#041d20",
      "titleBar.activeForeground": "#b2cacd",
      "titleBar.inactiveBackground": "#041d20",
      "titleBar.inactiveForeground": "#87a7ab",
      // ---------------------------
      // Custom title bar and menus
      // Note: These colors are currently only supported on Windows and Linux.
      // ---------------------------
      "menu.background": "#062e32",
      "menu.foreground": "#87a7ab",
      "menu.selectionBackground": "#0b515b",
      "menu.selectionForeground": "#40d4e7",
      "menu.selectionBorder": "#0b515b",
      "menu.separatorBackground": "#40d4e7",
      "menubar.selectionBackground": "#0b515b",
      "menubar.selectionForeground": "#40d4e7",
      "menubar.selectionBorder": "#0b515b",
      // ---------------------------
      // Snippets
      // ---------------------------
      "editor.snippetTabstopHighlightBackground": "#06292d",
      "editor.snippetTabstopHighlightBorder": "#073136",
      "editor.snippetFinalTabstopHighlightBackground": "#06292d",
      "editor.snippetFinalTabstopHighlightBorder": "#073136"
   },
   tokenColors: syntax
});
